# This is a basic workflow to help you get started with Actions

name: CI

permissions:
  contents: write

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags:
      - "*.*.*"
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Publish
        run: dotnet publish -c Release -o ./workspace/EGLProjectPathManager

      - name: Compress
        run: powershell Compress-Archive -Path .\workspace\EGLProjectPathManager\* -DestinationPath .\EGLProjectPathManager.zip

      - uses: actions/upload-artifact@v3
        with:
          name: EGLProjectPathManager
          path: ./workspace/EGLProjectPathManager/

      - name: Create a Release
        uses: elgohr/Github-Release-Action@v4
        #run: ./.github/workflows/entrypoint.sh
        #shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: Release

      #- uses: actions/download-artifact@v3
      #  with:
      #    name: EGLProjectPathManager
      #    path: ~/download/EGLProjectPathManager.zip

      #- name: Test
      #  run: dir -r  | % { if ($_.PsIsContainer) { $_.FullName + "\" } else { $_.FullName } }

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: EGLProjectPathManager.zip
